PassionProject_n01321102/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PassionProject_n01321102.Models
{
    public class Player
    {
        [Key, ScaffoldColumn(false)]
        public int PlayerID { get; set; }

        [Required, StringLength(255), Display(Name = "First Name")]
        public string PlayerFName { get; set; }

        [Required, StringLength(255), Display(Name = "Last Name")]
        public string PlayerLName { get; set; }

        [StringLength(255), Display(Name = "Discord Tag Name")]
        public string PlayerDiscord { get; set; }

        public int HasAvatar { get; set; }

        [StringLength(255), Display(Name = "Avatar")]
        public string PlayerAvatar { get; set; }

        public virtual ICollection<Game> Games { get; set; }

        // To Do : create a friendship Module
        // public virtual ICollection<Friendship> Friends { get; set; }
    }
}

PassionProject_n01321102/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using PassionProject_n01321102.Models;
using PassionProject_n01321102.Models.MultiModels;
using System.Diagnostics;
using System.IO;

namespace PassionProject_n01321102.Controllers
{
    public class GameController : Controller
    {
        //database object
        TeamBuilderContext dbContext = new TeamBuilderContext();
        // GET: Game
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            string gameList = "SELECT * FROM GAMES";
            IEnumerable<Game> games = dbContext.Games.SqlQuery(gameList);
            // return query
            return View(games);
            
        }

        public ActionResult Add()
        {
            GameMultiModel categories = new GameMultiModel();
            categories.Categories = dbContext.Categories.ToList();
            return View(categories);
        }

        public ActionResult Edit(int? id)
        {
            string editGame = "SELECT * FROM Games WHERE GameID = @gameid";
            GameMultiModel games = new GameMultiModel();
            games.Games = dbContext.Games.SqlQuery(editGame, new SqlParameter("@gameid", id)).FirstOrDefault();
            games.Categories = dbContext.Categories.ToList();
            return View(games);
        }

        [HttpPost]
        public ActionResult AddGame(string New_GameName, string New_GameDescription, int? New_GameCategory)
        {
            string addGame = "INSERT INTO Games (GameName, GameDescription, HasLogo) VALUES (@gameName, @gameDescription, @hasLogo)";

            //create a Sql Parameter Array
            SqlParameter[] sqlValues = new SqlParameter[3]
            {
                new SqlParameter("@gameName", SqlDbType.VarChar) { Value = New_GameName },
                new SqlParameter("@gameDescription", SqlDbType.VarChar) { Value = New_GameDescription },
                new SqlParameter("@hasLogo", SqlDbType.Int) { Value = 0 },
                //new SqlParameter("@gameCID", SqlDbType.Int) {Value = New_GameCategory}
            };

            dbContext.Database.ExecuteSqlCommand(addGame, sqlValues);

            
            // get the max ID after adding to database
            // source: https://stackoverflow.com/questions/315946/how-do-i-get-the-max-id-with-linq-to-entity
            // author: Thiago Valente
            int? New_GameID = dbContext.Games.Max(g => (int?)g.GameID);
            //Debug.WriteLine(newGameID);

            string addCategory = "INSERT INTO CategoryGames (Category_CategoryID, Game_GameID) VALUES (@gameCatID, @gameID)";
            SqlParameter[] categories = new SqlParameter[2] 
            {
                new SqlParameter("@gameID", SqlDbType.Int) {Value = New_GameID },
                new SqlParameter("@gameCatID", SqlDbType.Int) {Value = New_GameCategory}
            };

            // run the query
            dbContext.Database.ExecuteSqlCommand(addCategory, categories);

            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult Update(int? id, string GameName, string GameDescription, int gameCategory, HttpPostedFileBase GameLogo)
        {
            string editGame = "UPDATE Games SET GameName = @gameName, GameDescription = @gameDesc WHERE GameID = @gameid";

            // create a Sql Parameter Array
            SqlParameter[] sqlValues = new SqlParameter[5]
            {
                new SqlParameter("@gameName", SqlDbType.VarChar) { Value = GameName },
                new SqlParameter("@gameDesc", SqlDbType.VarChar) { Value = GameDescription },
                new SqlParameter("@gameid", SqlDbType.Int) { Value = id },

                // filler values this will be modified if user uploads an image
                new SqlParameter("@gameLogo", SqlDbType.VarChar) { Value = null },
                new SqlParameter("@hasLogo", SqlDbType.Int) { Value = 0 }
            };

            // TODO: Add game logo upload
            // I took this code from Christine's Example and modified it to suit my model

            // check if there is a posted file
            if (GameLogo != null)
            {
                // check the posted file
                if (GameLogo.ContentLength > 0)
                {
                    // modify the query
                    editGame = "UPDATE Games SET GameName = @gameName, GameDescription = @gameDesc, GameLogo = @gameLogo, HasLogo = @hasLogo WHERE GameID = @gameid";

                    //file extensioncheck taken from https://www.c-sharpcorner.com/article/file-upload-extension-validation-in-asp-net-mvc-and-javascript/
                    var valtypes = new[] { "jpeg", "jpg", "png", "gif" };
                    var extension = Path.GetExtension(GameLogo.FileName).Substring(1);

                    if (valtypes.Contains(extension))
                    {
                        //generic .img extension, web translates easily.
                        string logo = id + "." + extension;

                        //get a direct file path to imgs/authors/
                        string path = Path.Combine(Server.MapPath("~/images/games"), logo);

                        //save the file
                        GameLogo.SaveAs(path);

                        // add the values to insert
                        sqlValues[3] = new SqlParameter("@gameLogo", SqlDbType.VarChar) { Value = logo };
                        sqlValues[4] = new SqlParameter("@hasLogo", SqlDbType.Int) { Value = 1 };
                    }
                }
            }
            else
            {
                // splice the array if there is no posted file
                // code based from https://asp-net-example.blogspot.com/2013/10/c-example-array-remove-last-element.html
                // author: Saiful Alam
                Array.Resize(ref sqlValues, sqlValues.Length - 2);
            }

            dbContext.Database.ExecuteSqlCommand(editGame, sqlValues);

            // add to CategoryxGames Table
            string categoryQuery = "UPDATE CategoryGames SET Category_CategoryID = @gameCatID WHERE Game_GameID = @gameID";
            SqlParameter[] catValues = new SqlParameter[2]
            {
                new SqlParameter("@gameCatID", SqlDbType.Int) { Value = gameCategory },
                new SqlParameter("@gameID", SqlDbType.Int) { Value = id }
            };

            dbContext.Database.ExecuteSqlCommand(categoryQuery, catValues);

            // redirect to the game detail page
            return RedirectToAction("Summary/" + id);
        }

        public ActionResult Summary(int? id)
        {
            string gameSummary = "SELECT * FROM GAMES WHERE GameID = @gameid";

            // return result

            return View(dbContext.Games.SqlQuery(gameSummary,new SqlParameter("@gameid", id)).FirstOrDefault());
        }

        public ActionResult Delete(int? id)
        {
            string deleteGame = "DELETE FROM Games WHERE GameID = @gameid";

            dbContext.Database.ExecuteSqlCommand(deleteGame, new SqlParameter("@gameid", id));

            // return to game list
            return RedirectToAction("List");
        }
    }
}

PassionProject_n01321102/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using PassionProject_n01321102.Models;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Data;
using System.IO;

namespace PassionProject_n01321102.Controllers
{
    public class PlayerController : Controller
    {
        private TeamBuilderContext database = new TeamBuilderContext();
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult Register()
        {
            return View();
        }
        
        public ActionResult Profile(int id)
        {
            string query = "SELECT * FROM Players WHERE PlayerID = @playerid";
            return View(database.Players.SqlQuery(query, new SqlParameter("@playerid", id)).FirstOrDefault());
        }


        public ActionResult List()
        {
            return View(database.Players.ToList());
        }

        // Register an Account
        [HttpPost]
        public ActionResult Create(string New_PlayerFN, string New_PlayerLN, string New_PlayerDiscord)
        {
            string query = "INSERT INTO Players (PlayerFName, PlayerLName, PlayerDiscord, HasAvatar) " +
                "VALUES (@fname, @lname, @pldiscord, @hasAvatar)";

            // assign values to the sql parameter List
            // reference: https://stackoverflow.com/questions/425668/sql-parameter-collection/13676847
            // author: Drejc
            SqlParameter[] sqlValues = new SqlParameter[4]
            {
                new SqlParameter("@fname", SqlDbType.VarChar) { Value = New_PlayerFN},
                new SqlParameter("@lname", SqlDbType.VarChar) { Value =  New_PlayerLN},
                new SqlParameter("@pldiscord", SqlDbType.VarChar) { Value = New_PlayerDiscord},
                new SqlParameter("@hasAvatar", SqlDbType.Int) { Value = 0}
            };

            Debug.WriteLine(query);
            Debug.WriteLine(New_PlayerFN);
            Debug.WriteLine(New_PlayerLN);
            Debug.WriteLine(New_PlayerDiscord);
            Debug.WriteLine("after query");
            database.Database.ExecuteSqlCommand(query, sqlValues);
            return RedirectToAction("List");
        }

        public ActionResult Edit(int? id)
        {

            string query = "select * from Players where playerid = @id";
            return View(database.Players.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());

        }

        [HttpPost]
        public ActionResult Edit(int? id, string PlayerFName, string PlayerLName, string PlayerDiscord, HttpPostedFileBase PlayerAvatar)
        {
            string editPlayer = "update Players set PlayerFName = @fname, PlayerLName = @lname, PlayerDiscord = @pldiscord where PlayerID = @id";

            SqlParameter[] sqlValues = new SqlParameter[6] 
            {
                new SqlParameter("@fname", SqlDbType.VarChar) { Value = PlayerFName},
                new SqlParameter("@lname", SqlDbType.VarChar) { Value =  PlayerLName},
                new SqlParameter("@pldiscord", SqlDbType.VarChar) { Value = PlayerDiscord},
                new SqlParameter("@id", SqlDbType.Int) { Value = id},

                //these are just placeholders
                new SqlParameter("@playerAvatar", SqlDbType.VarChar) { Value = null},
                new SqlParameter("@hasAvatar", SqlDbType.Int) { Value = 0}
            };

            //TODO: Create image upload
            // I took this code from Christine's Example and modified it to suit my model
            if (PlayerAvatar.ContentLength > 0)
            {
                // modify the query
                editPlayer = "update Players set PlayerFName = @fname, PlayerLName = @lname, PlayerDiscord = @pldiscord, PlayerAvatar = @playerAvatar, HasAvatar = @hasAvatar where PlayerID = @id";

                // file extensioncheck taken from https://www.c-sharpcorner.com/article/file-upload-extension-validation-in-asp-net-mvc-and-javascript/
                // file  upload won't work without the attribute enctype="multipart/form-data"
                // source https://haacked.com/archive/2010/07/16/uploading-files-with-aspnetmvc.aspx/
                var valtypes = new[] { "jpeg", "jpg", "png", "gif" };
                var extension = Path.GetExtension(PlayerAvatar.FileName).Substring(1);

                if (valtypes.Contains(extension))
                {
                    //generic .img extension, web translates easily.
                    string image = id + "." + extension;

                    //get a direct file path to imgs/authors/
                    string path = Path.Combine(Server.MapPath("~/images/players"), image);

                    //save the file
                    PlayerAvatar.SaveAs(path);

                    // add the values to insert
                    sqlValues[4] = new SqlParameter("@playerAvatar", SqlDbType.VarChar) { Value = image };
                    sqlValues[5] = new SqlParameter("@hasAvatar", SqlDbType.Int) { Value = 1 };
                }
            }

            Debug.WriteLine(editPlayer);
            database.Database.ExecuteSqlCommand(editPlayer, sqlValues);

            return RedirectToAction("Profile/" + id);
        }

        public ActionResult Delete(int id)
        {
            //TODO: delete dependent tables form GuildxPlayer and PlayerXGames tables

            // Delete the player from the player table
            string query = "delete from Players where PlayerID = @id";

            database.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));

            return RedirectToAction("List");
        }

    }
}

PassionProject_n01321102/Views/Player/Delete.cshtml
@model PassionProject_n01321102.Models.Player

@{
    ViewBag.Title = "Delete Player";
}
<div class="col-md-8 col-md-offset-4">
    <h2>Delete player</h2>
    <div class="media">
        <img src="~/img/players/@Model.PlayerAvatar" class="mr-3" alt="...">
        <div class="media-body">
            <h5 class="mt-0">@Model.PlayerFName @Model.PlayerLName</h5>
            <p>Discord Tag: @Model.PlayerDiscord</p>
            <div class="col-md-6 col-md-offset-6">
                <input type="submit" value="Delete" class="btn btn-default" /> 
                @Html.ActionLink("Cancel", "Index",new { @class = "btn btn-alert" })
            </div>
        </div>
    </div>
</div>

PassionProject_n01321102/Views/Player/Edit.cshtml
@model PassionProject_n01321102.Models.Player

@{
    ViewBag.Title = "Edit Player";
}
<h2>Edit @Model.PlayerFName @Model.PlayerLName</h2>
<div class="col-md-12">
    <form method="post" action="/Player/Edit/@Model.PlayerID" enctype="multipart/form-data">
        <fieldset>
            <legend>
                Player Details
            </legend>
            <div class="form-group">
                <div class="col-md-4">
                    <label for="New_PlayerFN">First Name</label>
                </div>
                <div class="col-md-8">
                    <input type="text" name="PlayerFName" id="PlayerFName" class="form-control" value="@Model.PlayerFName" />
                    @Html.ValidationMessageFor(model => model.PlayerFName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4">
                    <label for="New_PlayerLN">Last Name</label>
                </div>
                <div class="col-md-8">
                    <input type="text" name="PlayerLName" id="PlayerLName" class="form-control" value="@Model.PlayerLName" />
                    @Html.ValidationMessageFor(model => model.PlayerLName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4">
                    <label for="New_Discord">Discord Tag</label>
                </div>
                <div class="col-md-8">
                    <input type="text" name="PlayerDiscord" id="PlayerDiscord" class="form-control" value="@Model.PlayerDiscord" />
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Upload an avatar</legend>
            <div class="col-md-6 col-md-offset-6">
                @if (Model.HasAvatar == 1)
                {
                    <img class="rounded" src="~/images/players/@Model.PlayerAvatar"/>
                }
                else
                {
                    <img width="128" src="~/images/players/default.png"/>
                }
            </div>
            <div class="form-group">
                <div class="col-md-8">
                    <input type="file" id="PlayerAvatar" name="PlayerAvatar">
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-4 col-md-8">
                    <input type="submit" value="Update" class="btn btn-primary" />
                </div>
            </div>
        </fieldset>
    </form>
</div>

PassionProject_n01321102/Views/Player/List.cshtml
@model IEnumerable<PassionProject_n01321102.Models.Player>

@{
    ViewBag.Title = "Players";
}

 <h2>Player List</h2>
<div class="col-md-8">
    @Html.ActionLink("Register an Account", "Register")
</div>

<table class="table table-striped">
    <tr>
        <th>
            Full Name
        </th>
        <th class="text-center">
            Discord Tag
        </th>
        <th class="text-right">
          User options
        </th>        
    </tr>

    @foreach (var players in Model)
    {
        <tr>
            <td>
                @if (players.HasAvatar == 1)
                {
                    <img width="40" src="~/images/players/@players.PlayerAvatar" class="rounded" alt="avatar" />
                }
                else
                {
                    <img width="40" src="~/images/players/default.png" class="rounded" alt="avatar" />
                }
                @players.PlayerFName @players.PlayerLName
            </td>
            <td class="text-center">
                @players.PlayerDiscord
            </td>
            <td class="text-right">
                @Html.ActionLink("Edit Player", "Edit", new { id = players.PlayerID }) |
                @Html.ActionLink("View Profile", "Profile", new { id = players.PlayerID }) |
                @Html.ActionLink("Delete", "Delete", new { id = players.PlayerID })
            </td>
        </tr>
    }

</table>

PassionProject_n01321102/Views/Player/Profile.cshtml
@model PassionProject_n01321102.Models.Player

@{
    ViewBag.Title = "Profile";
}
<div class="col-md-12 text-right">
    <a href="../Edit/@Model.PlayerID" class="btn btn-primary"> Edit Profile </a>
    <a href="../List" class="btn btn-dark"> Go Back </a>
</div>
<div>
    <div class="col-md-12 text-center">
        <div class="img-container">
            @if (Model.HasAvatar == 1)
            {
                <div class="img-container">
                    <img class="rounded" src="~/images/players/@Model.PlayerAvatar" />
                </div>
            }
            else
            {
                <img width="128" src="~/images/players/default.png"/>
            }
        </div>
        <h2>@Model.PlayerFName  @Model.PlayerLName</h2>
        <p> Discord Tag: @Model.PlayerDiscord </p>
    </div>
    <h4>Games Played by @Model.PlayerFName  @Model.PlayerLName</h4>
    <div class="gameList">
        @foreach (var game in Model.Games)
        {
            <div class="media">
                <img src="~/img/games/@game.GameLogo" class="mr-3" alt="...">
                <div class="media-body">
                    <h5 class="mt-0">@game.GameName</h5>
                    <p>@game.GameDescription</p>
                    @Html.ActionLink(game.GameName, "View/" + game.GameID, "Game")
                </div>
            </div>
        }
    </div>
</div>

PassionProject_n01321102/Views/Player/Register.cshtml
@model PassionProject_n01321102.Models.Player

@{
    ViewBag.Title = "Register A New Player";
}
<h2>Register a New Player</h2>
    <div class="col-md-12">
        <form method="post" action="/Player/Create">
            <fieldset>
                <legend>
                    Player Details
                </legend>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="New_PlayerFN">First Name</label>
                    </div>
                    <div class="col-md-8">
                        <input type="text" name="New_PlayerFN" id="New_PlayerFN" class="form-control" />
                        @Html.ValidationMessageFor(model => model.PlayerFName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="New_PlayerLN">Last Name</label>
                    </div>
                    <div class="col-md-8">
                        <input type="text" name="New_PlayerLN" id="New_PlayerLN" class="form-control" />
                        @Html.ValidationMessageFor(model => model.PlayerLName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="New_Discord">Discord Tag</label>
                    </div>
                    <div class="col-md-8">
                        <input type="text" name="New_PlayerDiscord" id="New_PlayerDiscord" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <input type="submit" value="Register" class="btn btn-primary" />
                    </div>
                </div>
            </fieldset>
        </form>
    </div>